### PR TITLE
remove title outline

### PR DESCRIPTION
**Pull request by jillyan**
for TPSVC-1562

**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
There is a blue outline when user click the title in list item.
http://screencast.com/t/aDSlq418ohM

**What is the new behavior?**

remove the outline

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by talend-glorieux** [comment]
It's not that good of an idea to remove the outline as it decreases accessibility.
To remove it only on mouse events but not on keyboard navigation you can use a library like [focus-outline-manager](https://www.npmjs.com/package/focus-outline-manager)

**Comment by jsomsanith** [comment]
But is it really necessary to remove it ?

**Comment by talend-glorieux** [comment]
@jsomsanith Well... it doesn't look really good ;)

**Comment by frassinier** [comment]
I propose to close this pull request until https://jira.talendforge.org/browse/TUX-192 is not done.
Feel free to reopen if needed.

**Pull request closed without merging**
