### PR TITLE
fix(immutable):added dev dependency

### PR DESCRIPTION
**Pull request by amaalej**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Immutable Lib was used but not added to the dependencies

**What is the new behavior?**
Added Immutable Lib to the dev dependecies.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by frassinier** [comment]
Where it's used? I don't see the problem since React ships this dependency. You can have conflicts therefore :/

**Comment by amaalej** [comment]
@frassinier it is used in stories/List

**Comment by sdwvit** [comment]
can we use react's immutable then?

**Comment by sdwvit** [comment]
After discussion with @amaalej he managed to fix error he was getting, though eslint requires listing of immutable.js in dependencies, cannot leave it unlisted or in devDependencies

**Comment by amaalej** [comment]
After a discussion with @sdwvit I added the dependency to package.json in order to avoid eslint error:
```
```

**Comment by sdwvit** [comment]
aw, you are totally right, I forgot this is not-a-production app

**Pull request merged**
