### PR TITLE
feat(Input): use react-debounce-input

### PR DESCRIPTION
**Pull request by frassinier**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Each time a key is down into input, `onKeyDown` handler is triggered

**What is the new behavior?**
`onKeyDown` handler is triggered each 0.3s and input must have 2 chars, at least.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://github.com/nkbt/react-debounce-input

### CODE REVIEW

**Comment by acateland** [comment]
I don't think a debounce strategy for network performance optimisation belong to the view stack.
It should belong to networking stack.

**Comment by frassinier** [comment]
This should mean each app will have to simplement the debounce strategy?

**Comment by acateland** [comment]
Deboucing stategy and timing could be different for each use case, not only Typeahead could use deboucing.

**Comment by frassinier** [comment]
@acateland I updated usage according to our discussion

**Comment by jmfrancois** [comment]
You forgot to update the Breaking change ... react-debounce-input is a new deps to install

**Pull request merged**
