### PR TITLE
fix(SidePanel): use 'Icon' component instead of 'i'

### PR DESCRIPTION
**Pull request by charlesnguyen**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

### CODE REVIEW

**Comment by frassinier** [comment]
@jmfrancois What do you propose instead?

**Comment by jsomsanith** [comment]
@jmfrancois do you mean an existing and registered defined icon ?

**Comment by jmfrancois** [comment]
May be I missed something but do we need to change the default icon on the app level ?

Don't forget also we have #81 

Why not just keeping this:

```javascript
<Icon name="fa-arrow-left" />
```

before fixing #81 

For me adding a props is not a fix, it's a feature.

**Comment by jsomsanith** [comment]
This implies that the project need font-awesome to use the side panel which is not the case in our project.
The icon needs to be included or to be injected by the app.

**Comment by jmfrancois** [comment]
What icon do you want here ?
I'm +1 to use an svg icon from talend-icons.
Fontawesome has to be removed from all existing components (including the List)
I'm -1 to have to choose which Icon has to be used

**Comment by jsomsanith** [comment]
Ok to fix it. We need to add a new icon to match the guidelines. Let's ask @maximenicoul to provide it

**Pull request merged**
