### PR TITLE
refactor(List): remove fontawesome use

### PR DESCRIPTION
**Pull request by jmfrancois**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Some components rely on fontawesome:

* List
* others ?

**What is the new behavior?**

No one rely on fontaweoms

Rely on TUX-172

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jmfrancois** [comment]
rely on TUX-172

**Comment by jsomsanith** [comment]
There are still components with `fa-` if you search this string in all src files

**Comment by jsomsanith** [comment]
@jmfrancois can you take a look at my last commit and if you approve, we can merge this PR.

**Comment by jmfrancois** [comment]
I will do that component per component.
So please all if you refactor a component take time to remove the font awesome on it ;)

**Pull request closed without merging**
